# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_image_module.html#examples
# https://www.redhat.com/en/blog/automate-podman-ansible
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_login_module.html#ansible-collections-containers-podman-podman-login-module

---
- name: "Instalar Podman - Login ACR - Desplegar contenedor del ACR"
  hosts: azurevm
  remote_user: azureadmin
  become: true
  vars_files:
    - variables.yml
  tasks:
    - name: Ejecutar un contenedor de Nginx con Podman
      ansible.builtin.command:
        cmd: podman run -d --name cp2nginx -p 8080:80 {{ ACR_NAME }}/nginx:cp2gmc 

    - name: Verificar que el contenedor esté en ejecución
      ansible.builtin.command:
        cmd: podman ps
      register: podman_ps_output

    - name: Mostrar contenedores en ejecución
      debug:
        var: podman_ps_output.stdout