# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html

---
- name: "Instalar Podman"
  hosts: localhost
  #remote_user: azureadmin
  remote_user: gmc
  become: true
  tasks:
    - name: Actualizar los paquetes APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalación
      apt:
        name: podman
        state: present

    - name: Verificar la instalación
      command: podman --version
      register: podman_version

    - name: Mostrar versión
      debug:
        var: podman_version.stdout