# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_image_module.html#examples
# https://www.redhat.com/en/blog/automate-podman-ansible
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_login_module.html#ansible-collections-containers-podman-podman-login-module

---
- name: "Instalar Podman - Login ACR - Desplegar contenedor del ACR"
  hosts: azurevm
  remote_user: azureadmin
  become: true
  vars_files:
    - variables.yml
  tasks:
    - name: Cargar las credenciales
      ansible.builtin.include_vars:
        file: azure_vault.yml
        name: credenciales_azure

    - name: Actualizar los paquetes APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalación
      apt:
        name: podman
        state: present

    - name: Verificar la instalación
      ansible.builtin.command:
        cmd: podman --version
      register: podman_version

    - name: Mostrar versión
      debug:
        var: podman_version.stdout

    - name: Configurar el archivo de registries.conf para buscar en Docker Hub
      lineinfile:
        path: /etc/containers/registries.conf
        regexp: '^unqualified-search-registries'
        line: 'unqualified-search-registries = ["docker.io"]'
        create: yes

    - name: Verificar que el archivo se haya modificado correctamente
      ansible.builtin.command:
        cmd: cat /etc/containers/registries.conf
      register: registries_conf

    - name: Mostrar el contenido del archivo registries.conf
      debug:
        var: registries_conf.stdout
    
    - name: Descargar la imagen
      containers.podman.podman_image:
        name: nginx
        tag: latest

    - name: Login en Azure
      containers.podman.podman_login:
        username: "{{ credenciales_azure.ACR_USR }}"
        password: "{{ credenciales_azure.ACR_PASS }}"
        registry: "{{ ACR_NAME }}"

    - name: Tagear la imagen con nuestra versión/ACR
      ansible.builtin.command:
        cmd: podman tag nginx:latest {{ ACR_NAME }}/nginx:cp2gmc

    - name: Verificar imagenes
      ansible.builtin.command:
        cmd: podman images
      register: podman_images_list

    - name: Mostrar imagenes podman
      debug:
        var: podman_images_list.stdout

    - name: Subir la imagen nginx a Azure ACR
      ansible.builtin.command:
        cmd: podman push {{ ACR_NAME }}/nginx:cp2gmc

    - name: Ejecutar un contenedor de Nginx con Podman
      ansible.builtin.command:
        cmd: podman run -d --name cp2nginx {{ ACR_NAME }}/nginx:cp2gmc

    - name: Verificar que el contenedor esté en ejecución
      ansible.builtin.command:
        cmd: podman ps
      register: podman_ps_output

    - name: Mostrar contenedores en ejecución
      debug:
        var: podman_ps_output.stdout